<h1>Lista de Pacientes</h1>
<?php
$id = 0;
$id_atual = '';
echo '<dl>';
foreach($pacientes as $paciente):    
    $id_atual = $paciente->getPacienteId();
    if($id != $id_atual){          
        echo '<dt>'.$paciente->getNome().' '.$paciente->getSobrenome().'</dt>';
        echo '<dt>Contatos:</dt>'; 
        echo '<dd>'.$paciente->getNomeContato().' - '.$paciente->getTelefone().'<dd/>';
    }else{
        echo '<dd>'.$paciente->getNomeContato().' - '.$paciente->getTelefone().'<dd/>';
    }  
    $id = $id_atual;
endforeach;
echo '</dl>';
?>
