<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Pacientes</h2>
            </div>
            <div class="card-body">
                <p>
                    <i class="fas fa-user-md fa-5x"></i> Dados do Paciente
                </p>
                <p><a href="<?= $this->url('paciente') ?>" class="btn btn-warning"> Listar Pacientes </a></p>
            </div>
        </div>
    </div>


</div>
